#!/usr/bin/env sh

echo "🚀 Running pre-push validation..."

echo "☑️  Running Test"
turbo run test
if [ $? -ne 0 ]; then
  echo "❌ Tests failed"
  exit 1
fi


# Run build to ensure everything compiles
echo "🏗️  Building project..."
turbo run build
if [ $? -ne 0 ]; then
  echo "❌ Build failed"
  exit 1
fi

echo "✅ All pre-push checks passed!"
